<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Visite__CLASSMETADATA__' => 0,
'App__Entity__Environnement__CLASSMETADATA__' => 1,
'Vich__UploaderBundle__Entity__File__CLASSMETADATA__' => 2,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Visite',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\VisiteRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'ville' => $o[2],
                        'pays' => $o[3],
                        'datecreation' => $o[4],
                        'note' => $o[5],
                        'avis' => $o[6],
                        'tempmin' => $o[7],
                        'tempmax' => $o[8],
                        'imageName' => $o[9],
                        'imageSize' => $o[10],
                        'updatedAt' => $o[11],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'ville' => 'ville',
                        'pays' => 'pays',
                        'datecreation' => 'datecreation',
                        'note' => 'note',
                        'avis' => 'avis',
                        'tempmin' => 'tempmin',
                        'tempmax' => 'tempmax',
                        'image_name' => 'imageName',
                        'image_size' => 'imageSize',
                        'updated_at' => 'updatedAt',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'ville' => 'ville',
                        'pays' => 'pays',
                        'datecreation' => 'datecreation',
                        'note' => 'note',
                        'avis' => 'avis',
                        'tempmin' => 'tempmin',
                        'tempmax' => 'tempmax',
                        'imageName' => 'image_name',
                        'imageSize' => 'image_size',
                        'updatedAt' => 'updated_at',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'visite',
                    ],
                ],
                'associationMappings' => [
                    [
                        'environnements' => $o[12],
                    ],
                ],
                'idGenerator' => [
                    $o[16],
                ],
                'name' => [
                    'App\\Entity\\Visite',
                    13 => 'visite_environnement',
                    'visite_id',
                    'environnement_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'date',
                    'integer',
                    'text',
                    'integer',
                    'integer',
                    'string',
                    'integer',
                    'datetime_immutable',
                ],
                'fieldName' => [
                    1 => 'id',
                    'ville',
                    'pays',
                    'datecreation',
                    'note',
                    'avis',
                    'tempmin',
                    'tempmax',
                    'imageName',
                    'imageSize',
                    'updatedAt',
                ],
                'columnName' => [
                    1 => 'id',
                    'ville',
                    'pays',
                    'datecreation',
                    'note',
                    'avis',
                    'tempmin',
                    'tempmax',
                    'image_name',
                    'image_size',
                    'updated_at',
                ],
                'length' => [
                    2 => 50,
                    50,
                ],
                'nullable' => [
                    4 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                'fetch' => [
                    12 => 2,
                ],
                'isOnDeleteCascade' => [
                    12 => true,
                ],
                'sourceEntity' => [
                    12 => 'App\\Entity\\Visite',
                ],
                'joinTable' => [
                    12 => $o[13],
                ],
                'joinTableColumns' => [
                    12 => [
                        'visite_id',
                        'environnement_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    12 => [
                        'visite_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    12 => [
                        'environnement_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    13 => [
                        $o[14],
                    ],
                ],
                'inverseJoinColumns' => [
                    13 => [
                        $o[15],
                    ],
                ],
                'onDelete' => [
                    14 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    14 => 'id',
                    'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    12 => 'environnements',
                ],
                'targetEntity' => [
                    12 => 'App\\Entity\\Environnement',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Environnement',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\EnvironnementRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'nom' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'environnement',
                    ],
                ],
                'idGenerator' => [
                    $o[3],
                ],
                'name' => [
                    'App\\Entity\\Environnement',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'nom',
                ],
                'columnName' => [
                    1 => 'id',
                    'nom',
                ],
                'length' => [
                    2 => 100,
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'Vich\\UploaderBundle\\Entity',
                ],
                'rootEntityName' => [
                    'Vich\\UploaderBundle\\Entity\\File',
                ],
                'isEmbeddedClass' => [
                    true,
                ],
                'fieldMappings' => [
                    [
                        'name' => $o[1],
                        'originalName' => $o[2],
                        'mimeType' => $o[3],
                        'size' => $o[4],
                        'dimensions' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'name' => 'name',
                        'original_name' => 'originalName',
                        'mime_type' => 'mimeType',
                        'size' => 'size',
                        'dimensions' => 'dimensions',
                    ],
                ],
                'columnNames' => [
                    [
                        'name' => 'name',
                        'originalName' => 'original_name',
                        'mimeType' => 'mime_type',
                        'size' => 'size',
                        'dimensions' => 'dimensions',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'file',
                    ],
                ],
                'idGenerator' => [
                    $o[6],
                ],
                'name' => [
                    'Vich\\UploaderBundle\\Entity\\File',
                ],
                'nullable' => [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                ],
                'type' => [
                    1 => 'string',
                    'string',
                    'string',
                    'integer',
                    'simple_array',
                ],
                'fieldName' => [
                    1 => 'name',
                    'originalName',
                    'mimeType',
                    'size',
                    'dimensions',
                ],
                'columnName' => [
                    1 => 'name',
                    'original_name',
                    'mime_type',
                    'size',
                    'dimensions',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
