<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJSxwDqj\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJSxwDqj/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJSxwDqj.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJSxwDqj\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJSxwDqj\App_KernelProdContainer([
    'container.build_hash' => 'JSxwDqj',
    'container.build_id' => '08ee70d6',
    'container.build_time' => 1767021706,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJSxwDqj');
