<?php

namespace ContainerCd09yKN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoyagesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VoyagesController' shared autowired service.
     *
     * @return \App\Controller\VoyagesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/VoyagesController.php';

        $container->services['App\\Controller\\VoyagesController'] = $instance = new \App\Controller\VoyagesController(($container->privates['App\\Repository\\VisiteRepository'] ?? $container->load('getVisiteRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\VoyagesController', $container));

        return $instance;
    }
}
