<?php

namespace ContainerJSxwDqj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_VichUploader_Command_MappingListClasses_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.vich_uploader.command.mapping_list_classes.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.vich_uploader.command.mapping_list_classes.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('vich:mapping:list-classes', [], 'Searches for uploadable classes.', false, #[\Closure(name: 'vich_uploader.command.mapping_list_classes', class: 'Vich\\UploaderBundle\\Command\\MappingListClassesCommand')] fn (): \Vich\UploaderBundle\Command\MappingListClassesCommand => ($container->privates['vich_uploader.command.mapping_list_classes'] ?? $container->load('getVichUploader_Command_MappingListClassesService')));
    }
}
