<?php

namespace ContainerJSxwDqj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEnvironnementControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\admin\AdminEnvironnementController' shared autowired service.
     *
     * @return \App\Controller\admin\AdminEnvironnementController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\admin\\AdminEnvironnementController'] = $instance = new \App\Controller\admin\AdminEnvironnementController(($container->privates['App\\Repository\\EnvironnementRepository'] ?? $container->load('getEnvironnementRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\admin\\AdminEnvironnementController', $container));

        return $instance;
    }
}
