<?php

namespace ContainerJSxwDqj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminVoyagesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\admin\AdminVoyagesController' shared autowired service.
     *
     * @return \App\Controller\admin\AdminVoyagesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\admin\\AdminVoyagesController'] = $instance = new \App\Controller\admin\AdminVoyagesController(($container->privates['App\\Repository\\VisiteRepository'] ?? $container->load('getVisiteRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\admin\\AdminVoyagesController', $container));

        return $instance;
    }
}
