<?php

namespace ContainerJSxwDqj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnvironnementRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EnvironnementRepository' shared autowired service.
     *
     * @return \App\Repository\EnvironnementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EnvironnementRepository'] = new \App\Repository\EnvironnementRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
