<?php

namespace ContainerW8FWmXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WwXhFGeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.wwXhFGe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wwXhFGe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contact' => ['privates', '.errored..service_locator.wwXhFGe.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.wwXhFGe": it needs an instance of "App\\Entity\\Contact" but this type has been excluded in "config/services.yaml".'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'contact' => 'App\\Entity\\Contact',
            'mailer' => '?',
        ]);
    }
}
