<?php

namespace ContainerW8FWmXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurableDirectoryNamerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Vich\UploaderBundle\Naming\ConfigurableDirectoryNamer' shared autowired service.
     *
     * @return \Vich\UploaderBundle\Naming\ConfigurableDirectoryNamer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Naming/DirectoryNamerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Naming/ConfigurableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Naming/ConfigurableDirectoryNamer.php';

        return $container->privates['Vich\\UploaderBundle\\Naming\\ConfigurableDirectoryNamer'] = new \Vich\UploaderBundle\Naming\ConfigurableDirectoryNamer();
    }
}
