<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW8FWmXN\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW8FWmXN/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerW8FWmXN.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerW8FWmXN\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerW8FWmXN\App_KernelTestDebugContainer([
    'container.build_hash' => 'W8FWmXN',
    'container.build_id' => 'c9d4f065',
    'container.build_time' => 1767018181,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW8FWmXN');
