<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'voyages' => [[], ['_controller' => 'App\\Controller\\VoyagesController::index'], [], [['text', '/voyages']], [], [], []],
    'voyages.sort' => [['champ', 'ordre'], ['_controller' => 'App\\Controller\\VoyagesController::sort'], [], [['variable', '/', '[^/]++', 'ordre', true], ['variable', '/', '[^/]++', 'champ', true], ['text', '/voyages/tri']], [], [], []],
    'voyages.findallequal' => [['champ'], ['_controller' => 'App\\Controller\\VoyagesController::findAllEqual'], [], [['variable', '/', '[^/]++', 'champ', true], ['text', '/voyages/recherche']], [], [], []],
    'voyages.showone' => [['id'], ['_controller' => 'App\\Controller\\VoyagesController::showOne'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voyages/voyage']], [], [], []],
    'admin.environnements' => [[], ['_controller' => 'App\\Controller\\admin\\AdminEnvironnementController::index'], [], [['text', '/admin/environnements']], [], [], []],
    'admin.environnement.suppr' => [['id'], ['_controller' => 'App\\Controller\\admin\\AdminEnvironnementController::suppr'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/environnement/suppr']], [], [], []],
    'admin.environnement.ajout' => [[], ['_controller' => 'App\\Controller\\admin\\AdminEnvironnementController::ajout'], [], [['text', '/admin/environnement/ajout']], [], [], []],
    'admin.voyages' => [[], ['_controller' => 'App\\Controller\\admin\\AdminVoyagesController::index'], [], [['text', '/admin']], [], [], []],
    'admin.voyage.suppr' => [['id'], ['_controller' => 'App\\Controller\\admin\\AdminVoyagesController::suppr'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/suppr']], [], [], []],
    'admin.voyage.edit' => [['id'], ['_controller' => 'App\\Controller\\admin\\AdminVoyagesController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/edit']], [], [], []],
    'admin.voyage.ajout' => [[], ['_controller' => 'App\\Controller\\admin\\AdminVoyagesController::ajout'], [], [['text', '/admin/ajout']], [], [], []],
    'App\Controller\AccueilController::index' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\ContactController::index' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'App\Controller\VoyagesController::index' => [[], ['_controller' => 'App\\Controller\\VoyagesController::index'], [], [['text', '/voyages']], [], [], []],
    'App\Controller\VoyagesController::sort' => [['champ', 'ordre'], ['_controller' => 'App\\Controller\\VoyagesController::sort'], [], [['variable', '/', '[^/]++', 'ordre', true], ['variable', '/', '[^/]++', 'champ', true], ['text', '/voyages/tri']], [], [], []],
    'App\Controller\VoyagesController::findAllEqual' => [['champ'], ['_controller' => 'App\\Controller\\VoyagesController::findAllEqual'], [], [['variable', '/', '[^/]++', 'champ', true], ['text', '/voyages/recherche']], [], [], []],
    'App\Controller\VoyagesController::showOne' => [['id'], ['_controller' => 'App\\Controller\\VoyagesController::showOne'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voyages/voyage']], [], [], []],
    'App\Controller\admin\AdminEnvironnementController::index' => [[], ['_controller' => 'App\\Controller\\admin\\AdminEnvironnementController::index'], [], [['text', '/admin/environnements']], [], [], []],
    'App\Controller\admin\AdminEnvironnementController::suppr' => [['id'], ['_controller' => 'App\\Controller\\admin\\AdminEnvironnementController::suppr'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/environnement/suppr']], [], [], []],
    'App\Controller\admin\AdminEnvironnementController::ajout' => [[], ['_controller' => 'App\\Controller\\admin\\AdminEnvironnementController::ajout'], [], [['text', '/admin/environnement/ajout']], [], [], []],
    'App\Controller\admin\AdminVoyagesController::index' => [[], ['_controller' => 'App\\Controller\\admin\\AdminVoyagesController::index'], [], [['text', '/admin']], [], [], []],
    'App\Controller\admin\AdminVoyagesController::suppr' => [['id'], ['_controller' => 'App\\Controller\\admin\\AdminVoyagesController::suppr'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/suppr']], [], [], []],
    'App\Controller\admin\AdminVoyagesController::edit' => [['id'], ['_controller' => 'App\\Controller\\admin\\AdminVoyagesController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/edit']], [], [], []],
    'App\Controller\admin\AdminVoyagesController::ajout' => [[], ['_controller' => 'App\\Controller\\admin\\AdminVoyagesController::ajout'], [], [['text', '/admin/ajout']], [], [], []],
];
