<?php

namespace ContainerI9mGOpr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEnvironnementControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\admin\AdminEnvironnementController' shared autowired service.
     *
     * @return \App\Controller\admin\AdminEnvironnementController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/admin/AdminEnvironnementController.php';

        $container->services['App\\Controller\\admin\\AdminEnvironnementController'] = $instance = new \App\Controller\admin\AdminEnvironnementController(($container->privates['App\\Repository\\EnvironnementRepository'] ?? $container->load('getEnvironnementRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\admin\\AdminEnvironnementController', $container));

        return $instance;
    }
}
