<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK3v2HJx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK3v2HJx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK3v2HJx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK3v2HJx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK3v2HJx\App_KernelDevDebugContainer([
    'container.build_hash' => 'K3v2HJx',
    'container.build_id' => 'c98f1ee4',
    'container.build_time' => 1775001981,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK3v2HJx');
