<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKVlNTgc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKVlNTgc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKVlNTgc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKVlNTgc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKVlNTgc\App_KernelDevDebugContainer([
    'container.build_hash' => 'KVlNTgc',
    'container.build_id' => 'd7bd5093',
    'container.build_time' => 1775001174,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKVlNTgc');
