<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Visite extends \App\Entity\Visite implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avis' => [parent::class, 'avis', null],
        "\0".parent::class."\0".'datecreation' => [parent::class, 'datecreation', null],
        "\0".parent::class."\0".'environnements' => [parent::class, 'environnements', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null],
        "\0".parent::class."\0".'imageName' => [parent::class, 'imageName', null],
        "\0".parent::class."\0".'imageSize' => [parent::class, 'imageSize', null],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null],
        "\0".parent::class."\0".'pays' => [parent::class, 'pays', null],
        "\0".parent::class."\0".'tempmax' => [parent::class, 'tempmax', null],
        "\0".parent::class."\0".'tempmin' => [parent::class, 'tempmin', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'ville' => [parent::class, 'ville', null],
        'avis' => [parent::class, 'avis', null],
        'datecreation' => [parent::class, 'datecreation', null],
        'environnements' => [parent::class, 'environnements', null],
        'id' => [parent::class, 'id', null],
        'imageFile' => [parent::class, 'imageFile', null],
        'imageName' => [parent::class, 'imageName', null],
        'imageSize' => [parent::class, 'imageSize', null],
        'note' => [parent::class, 'note', null],
        'pays' => [parent::class, 'pays', null],
        'tempmax' => [parent::class, 'tempmax', null],
        'tempmin' => [parent::class, 'tempmin', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'ville' => [parent::class, 'ville', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
